/*
    Boost Software License - Version 1.0 - August 17, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

#pragma once

#include <littl/BaseIO.hpp>
#include <bleb/byteio.hpp>

namespace li
{
    class SeekableIOStreamByteIO : public bleb::ByteIO
    {
        public:
            SeekableIOStreamByteIO(SeekableIOStream* ios = nullptr) : ios(ios) {}

            void set(SeekableIOStream* ios) { this->ios = ios; }

            virtual void close() override {}
            virtual uint64_t getSize() override { return ios->getSize(); }

            virtual bool getBytesAt(uint64_t pos, uint8_t* buffer, size_t count) override
            {
                return ios->setPos(pos) && ios->read(buffer, count) == count;
            }

            virtual bool setBytesAt(uint64_t pos, const uint8_t* buffer, size_t count) override
            {
                return ios->setPos(pos) && ios->write(buffer, count) == count;
            }

            virtual bool clearBytesAt(uint64_t pos, uint64_t count) override
            {
                static const uint8_t empty[256] = {};

                while (count > sizeof(empty)) {
                    if (!setBytesAt(pos, empty, sizeof(empty)))
                        return false;

                    pos += sizeof(empty);
                    count -= sizeof(empty);
                }

                if (!setBytesAt(pos, empty, count))
                    return false;

                return true;
            }

        private:
            SeekableIOStream* ios;
};
}
